# Generated by Django 5.1.2 on 2024-10-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
